### ISSUE TITLE
simplesmtp don't show up the FROM and TO mail headers on the envelope object for the "end" event

### ISSUE THREAD

**Issue by lirantal** [andris9/simplesmtp#97]
In advanced server configuration for simplesmtp, the FROM and TO fields which are available on events like "start" and "data" don't show up in the "end" event.

Is this by design or a defect?

**Comment by andris9** [comment]
Envelope info should be available for `startData`, `data` and `dataReady` events. `end` is not related to the transaction (multiple transactions can happen trough a single connection)

**Comment by lirantal** [comment]
Thanks, makes sense. I did already change my code to use ```dataReady```` after finding out it's unavailable in the ```end``` event.
