### ISSUE TITLE
Command not recognized. Trying to handle email content HTML as a command.

### ISSUE THREAD

**Issue by jboga** [andris9/simplesmtp#98]
Hi Andris,
first of all thanks for your module.
I run into an issue where the body of an email is sometimes handled as a command that cause the rejection of the email (I got a 'Command not recognized' error, for example: Unknown command: </td> { from: 'dingding+bncBCSZ3YG74ICBBYNLUWXAKGQEL4QTXJA@frontapp.com').

I'm trying to get the original email from my customer but with no success at the moment.
I guess the error is coming from the sender server which do not properly send the data as expected (with an incorrect end of line and/or end of data) but I was wondering if there was a setting that I may have miss.
Do you have any idea of what could be the cause or if there is something I can change on simplesmtp to correctly handle that case?
Thanks for your help and for your modules (simeplsmtp, nodemailer, mailparser,... ;-) )
Jeremy

**Comment by andris9** [comment]
Are you building a SMTP server or using simplemstp as a client? If you are building a server then I'd suggest you to move from simplesmtp to (smtp-server)[https://github.com/andris9/smtp-server] module which does not have the problems that simplesmtp has.

**Comment by jboga** [comment]
Andris,
we are building a SMTP server. We can switch to smtp-server at the moment as we are still using Node 0.10. But we plan to switch in a short-term period.
Thanks again.
